[package]
name = "modular"
version = "0.1.0"
authors = ["Theo Garefalakis <tgaref@gmail.com>"]
edition = "2018"

[dependencies]
ramp = "0.5.1"
factor = { path = "../factor" }
arithfunc = { path = "../arithfunc" }